### ISSUE TITLE
docker support

### ISSUE THREAD

**Issue by mcollina** [nearform/lttng-vagrant#2]
Will it be possible to have this running inside a docker container on Mac OS X with the latest boot2docker?

**Comment by GlenTiki** [comment]
I'm working on getting a demo ready for the next nodejs meetup in dublin, but when I finish that, this will be my next priority. You're welcome to mess with it if you get a chance, but I won't be able to address this until much later this month.

**Comment by mcollina** [comment]
no worries ;). I will wait for you!

**Comment by GlenTiki** [comment]
:+1:
